services:
  rosc-dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - rosc-target:/workspace/target
    stdin_open: true
    tty: true

volumes:
  cargo-registry:
  cargo-git:
  rosc-target:
